config/routes.rb
NintyNineCats::Application.routes.draw do
  resources :cats
  resources :cat_rental_requests do
    member do
      post 'approve'
      post 'deny'
    end
  end
  resources :users, :only => [:create, :new]
  resource :session, :only => [:create, :destroy, :new]

end

app/models/cat.rb
class Cat < ActiveRecord::Base
  attr_accessible :age, :birth_date, :color, :name, :sex, :user_id

  validates :age, :birth_date, :color, :name, :sex, :presence => true
  validates :color, inclusion: { in: ["black","white","brown","grey"] }
  validates :sex, inclusion: { in: ["m","f"] }

  has_many(
    :rental_requests,
    class_name: "CatRentalRequest",
    foreign_key: "cat_id",
    primary_key: "id",
    :dependent => :destroy
  )

  belongs_to :user



end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  attr_accessible :cat_id, :start_date, :end_date, :status

  before_validation :status_check, on: :create
  validates :cat_id, :start_date, :end_date, :status, presence: true
  validates :status, inclusion: { in: ["pending","approved","denied"] }
  validate :overlapping_approved_requests

  belongs_to(
    :cat,
    class_name: "Cat",
    foreign_key: "cat_id",
    primary_key: "id"
  )

  def status_check
    self.status ||= "pending"
  end

  def pending?
    self.status == "pending"
  end

  def overlapping_requests
    overlapping = []
    requests = self.class.all << self
    requests.uniq!
    requests.each_with_index do |request, index|
      reqs = requests[(index + 1)..-1]
      reqs.each do |request2|
        if (request2.start_date > request.start_date && request2.start_date < request.end_date) ||
          (request2.end_date > request.start_date && request2.end_date < request.end_date)
          overlapping << [request, request2]
        end
      end
    end
    overlapping
  end

  def overlapping_approved_requests
    if overlapping_requests.any? { |request1, request2| request1.status == "approved" && request2.status == "approved" }
      errors.add(:base, "Request overlaps with another approved request!")
    end
  end

  def self.requests_for_cat_id(cat_id)
    find_all_by_cat_id(cat_id)
  end

  def approve!
    self.status = "approved"
    requests_to_deny = []
    overlapping = overlapping_requests
    overlapping.each do |request1, request2|
      if request1 == self
        requests_to_deny << request2
      elsif request2 == self
        requests_to_deny << request1
      end
    end
    self.class.transaction do
      requests_to_deny.each { |request| request.deny! }
      self.save!
    end
  end

  def deny!
    self.status = "denied"
    save!
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :user_name, :password_digest, :session_token

  has_many :cats

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def self.find_by_credentials(user_name, password)
    @user = User.find_by_user_name(user_name)

    if !@user.nil? && @user.is_password?(password)
      @user
    else
      @user = nil
    end
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
  end

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include SessionsHelper
  include CatsHelper
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  before_filter :owns_cat!, only: [:approve, :deny]

  def new
    @cats = Cat.all
    render :request_form
  end

  def create
    @rental_request = CatRentalRequest.new(params[:rental_request])
    if @rental_request.save
      redirect_to cat_url(Cat.find_by_id(@rental_request.cat_id))
    else
      redirect_to new_cat_rental_request_url
    end
  end

  def approve
    rental_request = CatRentalRequest.find(params[:id])
    rental_request.approve!
    redirect_to cat_url(Cat.find_by_id(rental_request.cat_id))
  end

  def deny
    rental_request = CatRentalRequest.find(params[:id])
    rental_request.deny!
    redirect_to cat_url(Cat.find_by_id(rental_request.cat_id))
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_filter :require_current_user!, :only => [:edit, :update, :new, :create]
  before_filter :owns_cat!, :only => [:edit, :update]


#  cat.owns_cat

  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find_by_id(params[:id])
    @rental_requests = CatRentalRequest.requests_for_cat_id(@cat.id)
    if @cat
      render :show
    else
      redirect_to cats_url
    end
  end

  def new
    @cat = Cat.new(age: 0, birth_date: Time.now.to_date, color: "black", name: "", sex: 'm')
    render :form
  end

  def create
    @cat = Cat.new(params[:cat])
    @cat.user_id = current_user.id
    if @cat.save
      redirect_to cat_url(@cat)
    else
      redirect_to cats_url('new')
    end
  end

  def edit
    @cat = Cat.find_by_id(params[:id])
    if @cat
      render :form
    else
      redirect_to cats_url
    end
  end

  def update
    @cat = Cat.find_by_id(params[:id])
    if @cat
      @cat.age = params[:cat][:age]
      @cat.birth_date = params[:cat][:birth_date]
      @cat.color = params[:cat][:color]
      @cat.name = params[:cat][:name]
      @cat.sex = params[:cat][:sex]
      if @cat.save
        redirect_to cat_url(@cat)
      else
        redirect_to edit_cat_url(@cat)
      end
    else
      redirect_to cats_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    flash[:errors] = [request.location.city]
    render :new
  end

  def create
    @user = User.find_by_credentials(
    params[:user][:user_name],
    params[:user][:password])

    if !@user.nil?
      login_user!(@user)
      redirect_to cats_url
    else
      flash[:errors] = []
      flash[:errors] << "Your login failed"
      flash[:errors] << "And you suck"
      render :new
    end
  end

  def destroy
    logout_current_user!

    render :new

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render :new
  end
# form password = 'dog'
#
# params[:user][:password]
# params[:user][:username]
#
# User.new(:password => 'dog', username: 'rob')
# User.new(:password_digest => 'dsfhalsdifasdhj2425', username: 'rob')



  def create

    @user = User.new
    @user.user_name = (params[:user][:user_name])
    @user.password= (params[:user][:password])
    login_user!(@user)
    #@user.password = params[:user][:password]


    if @user.save
      redirect_to cats_url
    else
      render :new
    end


  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/helpers/cats_helper.rb
module CatsHelper

  def owns_cat!
    redirect_to cats_url if current_user.nil? || current_user.id != Cat.find_by_id(params[:id]).user_id
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by_session_token(session[:session_token])
  end


  def logout_current_user!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def login_user!(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
  end

  def require_current_user!
    redirect_to new_session_url if current_user.nil?
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cat_rental_requests/request_form.html.erb
<h2>Rent-a-cat</h2>
<form action="/cat_rental_requests" method="post">
  <label for="cat_id">Cat</label>
  <select name="rental_request[cat_id]">
		<% @cats.each do |cat| %>
    <option value="<%= cat.id %>"><%= cat.name %></option>
		<% end %>
  </select>
  <br>

  <label for="start_date">Start date</label>
  <input name="rental_request[start_date]" id="start_date" type="date"></input>
	<br>

  <label for="end_date">End date</label>
  <input name="rental_request[end_date]" id="end_date" type="date"></input>
	<br>

	<input type='submit' value='Submit'>
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
</form>

app/views/cats/form.html.erb
<h2><%= @cat.persisted? ? "Edit #{@cat.name}" : "New cat" %></h2>
<form action="<%= @cat.persisted? ? "/cats/#{@cat.id}" : "/cats"%>" method="post">
	<input name="_method" type="hidden" value="<%= @cat.persisted? ? "put" : "post"%>" />

  <label for="cat_name">Name</label>
  <input name="cat[name]" id="cat_name" type="text" value="<%= @cat.name %>">
  <br>

  <label for="cat_age">Age</label>
  <input name="cat[age]" id="cat_age" type="number" value="<%= @cat.age %>">
  <br>

  <label>Sex</label>
  <div>
    <input name="cat[sex]" id="cat_sex_m" type="radio" value="m"<%= " checked" if @cat.sex == "m" %>>
    <label for="cat_sex_m">Male</label>
    <input name="cat[sex]" id="cat_sex_f" type="radio" value="f"<%= " checked" if @cat.sex == "f" %>>
    <label for="cat_sex_f">Female</label>
  </div>
  <br>

  <label for="cat_color">Color</label>
  <select name="cat[color]">
    <option value="brown"<%= " selected" if @cat.color == "brown" %>>brown</option>
    <option value="black"<%= " selected" if @cat.color == "black" %>>black</option>
    <option value="white"<%= " selected" if @cat.color == "white" %>>white</option>
		<option value="grey"<%= " selected" if @cat.color == "grey" %>>grey</option>
  </select>
  <br>

  <label for="cat_birth_date">Birth date</label>
  <input name="cat[birth_date]" id="cat_birth_date" type="date" value="<%= @cat.birth_date %>"></input>
	<br>

  <input type="submit" value="<%= @cat.persisted? ? "Save changes" : "Build my cat!" %>">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
</form>

app/views/cats/index.html.erb
<h2>Cats</h2>
<!-- welcome bob -->
<% if !current_user.nil? %>
<h3>Welcome <%= current_user.user_name %>!</h3>
<% end %>

<ul>
  <% @cats.each do |cat| %>
	  <li><%= link_to cat.name, "#{cats_url}/#{cat.id}" %></li>
  <% end %>
</ul>

app/views/cats/show.html.erb
<h2><%= @cat.name %></h2>

<ul>
   <li>Age: <%= @cat.age %></li>
	 <li>Birth date: <%= @cat.birth_date %></li>
	 <li>Color: <%= @cat.color %></li>
	 <li>Name: <%= @cat.name %></li>
	 <li>Sex: <%= @cat.sex %></li>
	 <li>Owner: <%= @cat.user.user_name %></li>
</ul>


	<% if !current_user.nil? && @cat.user_id == current_user.id %>
	<h3>Rental requests</h3>
	<ul>
		<% @rental_requests.each do |rental_request| %>
		<li>
			From <%= rental_request.start_date %> to <%= rental_request.end_date %>
			<% if rental_request.pending?%>
			<%= button_to "Approve", approve_cat_rental_request_url(rental_request), :method => :post %>
			<%= button_to "Deny", deny_cat_rental_request_url(rental_request), :method => :post %>
			<%else%>
			<%= ": #{rental_request.status}" %>
			<%end%>
		</li>
		<% end %>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NintyNineCats</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if flash[:errors] %>
   <% flash[:errors].each do |error| %>
	 <%= error %><br>
	 <% end %>
<% end %>

<%= request.location.city =%>



<%= yield %>



<% if !current_user.nil? %>
<h3><%= current_user.user_name %></h3>
<form action=" <%= session_url %>" method="POST">
<input name="_method" type="hidden" value="delete" />
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

	<p><input type="submit" value="Logout"></p>
</form>
<% end %>

</body>
</html>

app/views/users/new.html.erb
<h2>Create New User</h2>
<form action="/users" method="post">
	<input name="_method" type="hidden" value="" />

  <label for="user_user_name">Username: </label>

  <input name="user[user_name]" id="user_user_name" type="text" value="">
  <br>

  <label for="user_password">Password: </label>
  <input name="user[password]" id="user_password" type="text" value="">
  <br>


  <input type="submit" value="Register">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
</form>